#!/bin/bash

external=/sys/class/drm/card0-HDMI-A-1/status

lock() {
    if [ `cat $external` = 'disconnected' ]
    then
        i3lock -i ~/lock.png
    else
        i3lock -i ~/dlock.png
    fi
}

turn_on_wifi() {
    sudo rfkill unblock wifi
    sudo ifconfig wlan0 up
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && sudo pm-suspend
        turn_on_wifi
        ;;
    hibernate)
        lock && sudo pm-hibernate
        turn_on_wifi
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
        sudo poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
